export default {
  slug: 'ssb4',
  route: 'ssb4',
  name: 'Super Smash Bros. 4',
  shortName: 'SSB4',
  console: 'Wii U',
  year: 2014,
  notices: [
    {
      id: '2019/01/15',
      message: `
        <p>
          This is the latest and most widely-accepted tier list for
          <a href="https://www.ssbwiki.com/Super_Smash_Bros._4">Super Smash Bros. 4</a>
          from Nintendo Wii U, produced by the Smash Back Room and last updated
          on December 11th, 2017. Reflects version 1.1.7 of the game.
        </p>
        <p>
          To know more about how these tier lists are made check out the "Tier list" article
          on <a href="https://www.ssbwiki.com/tier_list">the Smash Wiki</a>.
        </p>
      `,
    },
  ],
  tiers: [
    { name: 'S', color: '#d0021b' },
    { name: 'A', color: '#f5a623' },
    { name: 'B', color: '#f8e71c' },
    { name: 'C', color: '#7ed321' },
    { name: 'D', color: '#50e3c2' },
    { name: 'E', color: '#4a90e2' },
    { name: 'F', color: '#bd10e0' },
    { name: 'G', color: '#9013fe' },
  ],
  roster: [
    {
      slug: 'bayonetta',
      name: 'Bayonetta',
      color: '#a5a1e0',
      tier: 'S',
    },
    {
      slug: 'cloud',
      name: 'Cloud',
      color: '#409384',
      tier: 'S',
    },
    {
      slug: 'diddy-kong',
      name: 'Diddy Kong',
      color: '#e15951',
      tier: 'S',
    },
    {
      slug: 'sheik',
      name: 'Sheik',
      color: '#746fd0',
      tier: 'A',
    },
    {
      slug: 'rosalina',
      name: 'Rosalina',
      color: '#9cded5',
      tier: 'A',
    },
    {
      slug: 'zero-suit-samus',
      name: 'Zero Suit Samus',
      color: '#1e5ba4',
      tier: 'A',
    },
    {
      slug: 'fox',
      name: 'Fox',
      color: '#266bc2',
      tier: 'A',
    },
    {
      slug: 'sonic',
      name: 'Sonic',
      color: '#649dec',
      tier: 'A',
    },
    {
      slug: 'mario',
      name: 'Mario',
      color: '#d04c4a',
      tier: 'A',
    },
    {
      slug: 'mewtwo',
      name: 'Mewtwo',
      color: '#7859bd',
      tier: 'A',
    },
    {
      slug: 'marth',
      name: 'Marth',
      color: '#5ba8c8',
      tier: 'A',
    },
    {
      slug: 'ryu',
      name: 'Ryu',
      color: '#d0504d',
      tier: 'A',
    },
    {
      slug: 'corrin',
      name: 'Corrin',
      color: '#62a7c0',
      tier: 'B',
    },
    {
      slug: 'lucina',
      name: 'Lucina',
      color: '#7ea6c7',
      tier: 'B',
    },
    {
      slug: 'pikachu',
      name: 'Pikachu',
      color: '#f7c143',
      tier: 'B',
    },
    {
      slug: 'meta-knight',
      name: 'Meta Knight',
      color: '#2e3e76',
      tier: 'B',
    },
    {
      slug: 'lucario',
      name: 'Lucario',
      color: '#b8e3fc',
      tier: 'B',
    },
    {
      slug: 'luigi',
      name: 'Luigi',
      color: '#5ea444',
      tier: 'B',
    },
    {
      slug: 'captain-falcon',
      name: 'Captain Falcon',
      color: '#8d8bdc',
      tier: 'B',
    },
    {
      slug: 'peach',
      name: 'Peach',
      color: '#f5c9f0',
      tier: 'B',
    },
    {
      slug: 'olimar',
      name: 'Olimar',
      color: '#cdefb0',
      tier: 'C',
    },
    {
      slug: 'donkey-kong',
      name: 'Donkey Kong',
      color: '#fada4a',
      tier: 'C',
    },
    {
      slug: 'toon-link',
      name: 'Toon Link',
      color: '#a6d160',
      tier: 'C',
    },
    {
      slug: 'bowser',
      name: 'Bowser',
      color: '#44745e',
      tier: 'C',
    },
    {
      slug: 'villager',
      name: 'Villager',
      color: '#5da972',
      tier: 'C',
    },
    {
      slug: 'greninja',
      name: 'Greninja',
      color: '#5673a5',
      tier: 'C',
    },
    {
      slug: 'megaman',
      name: 'Megaman',
      color: '#85c1e0',
      tier: 'C',
    },
    {
      slug: 'ness',
      name: 'Ness',
      color: '#de423d',
      tier: 'C',
    },
    {
      slug: 'lucas',
      name: 'Lucas',
      color: '#e06833',
      tier: 'C',
    },
    {
      slug: 'duck-hunt',
      name: 'Duck Hunt',
      color: '#8d5d3a',
      tier: 'D',
    },
    {
      slug: 'link',
      name: 'Link',
      color: '#c2cf72',
      tier: 'D',
    },
    {
      slug: 'pit',
      name: 'Pit',
      color: '#7db3d4',
      tier: 'D',
    },
    {
      slug: 'dark-pit',
      name: 'Dark Pit',
      color: '#a473e4',
      tier: 'D',
    },
    {
      slug: 'yoshi',
      name: 'Yoshi',
      color: '#83cd65',
      tier: 'D',
    },
    {
      slug: 'shulk',
      name: 'Shulk',
      color: '#d6647a',
      tier: 'D',
    },
    {
      slug: 'rob',
      name: 'R.O.B.',
      color: '#b3b9be',
      tier: 'D',
    },
    {
      slug: 'robin',
      name: 'Robin',
      color: '#c388d9',
      tier: 'D',
    },
    {
      slug: 'samus',
      name: 'Samus',
      color: '#353f56',
      tier: 'D',
    },
    {
      slug: 'mr-game-watch',
      name: 'Mr. Game & Watch',
      color: '#a6a392',
      tier: 'E',
    },
    {
      slug: 'ike',
      name: 'Ike',
      color: '#b74f3e',
      tier: 'E',
    },
    {
      slug: 'wario',
      name: 'Wario',
      color: '#f7cc64',
      tier: 'E',
    },
    {
      slug: 'roy',
      name: 'Roy',
      color: '#74b65b',
      tier: 'E',
    },
    {
      slug: 'charizard',
      name: 'Charizard',
      color: '#e66e39',
      tier: 'E',
    },
    {
      slug: 'little-mac',
      name: 'Little Mac',
      color: '#49755c',
      tier: 'E',
    },
    {
      slug: 'palutena',
      name: 'Palutena',
      color: '#91e5c1',
      tier: 'E',
    },
    {
      slug: 'pac-man',
      name: 'Pac Man',
      color: '#f0b252',
      tier: 'F',
    },
    {
      slug: 'falco',
      name: 'Falco',
      color: '#69b1df',
      tier: 'F',
    },
    {
      slug: 'bowser-jr',
      name: 'Bowser Jr.',
      color: '#d0cd55',
      tier: 'F',
    },
    {
      slug: 'dr-mario',
      name: 'Dr. Mario',
      color: '#e86c6d',
      tier: 'F',
    },
    {
      slug: 'kirby',
      name: 'Kirby',
      color: '#f2c1c4',
      tier: 'F',
    },
    {
      slug: 'wii-fit-trainer',
      name: 'Wii Fit Trainer',
      color: '#99d481',
      tier: 'F',
    },
    {
      slug: 'king-dedede',
      name: 'King Dedede',
      color: '#fde87b',
      tier: 'G',
    },
    {
      slug: 'ganondorf',
      name: 'Ganondorf',
      color: '#7d7a97',
      tier: 'G',
    },
    {
      slug: 'zelda',
      name: 'Zelda',
      color: '#a278b6',
      tier: 'G',
    },
    {
      slug: 'jigglypuff',
      name: 'Jigglypuff',
      color: '#e18ae5',
      tier: 'G',
    },
  ],
};
