export default {
  slug: 'ssbu',
  route: 'ultimate',
  name: 'Super Smash Bros. Ultimate',
  shortName: 'Ultimate',
  console: 'Switch',
  year: 2018,
  tiers: [
    { name: 'S', color: '#d0021b' },
    { name: 'A', color: '#f5a623' },
    { name: 'B', color: '#7ed321' },
    { name: 'C', color: '#50e3c2' },
    { name: 'D', color: '#4a90e2' },
  ],
  roster: [
    {
      slug: 'inkling',
      name: 'Inkling',
      color: '#de437d',
      tier: 'S',
    },
    {
      slug: 'chrom',
      name: 'Chrom',
      color: '#b4b4cd',
      tier: 'S',
    },
    {
      slug: 'pikachu',
      name: 'Pikachu',
      color: '#f6ba44',
      tier: 'S',
    },
    {
      slug: 'olimar',
      name: 'Olimar',
      color: '#d3edb6',
      tier: 'S',
    },
    {
      slug: 'lucina',
      name: 'Lucina',
      color: '#85a5c4',
      tier: 'S',
    },
    {
      slug: 'marth',
      name: 'Marth',
      color: '#6da7c5',
      tier: 'S',
    },
    {
      slug: 'peach',
      name: 'Peach',
      color: '#f5c9f0',
      tier: 'S',
    },
    {
      slug: 'daisy',
      name: 'Daisy',
      color: '#e9bc4d',
      tier: 'S',
    },
    {
      slug: 'lucario',
      name: 'Lucario',
      color: '#4794c1',
      tier: 'S',
    },
    {
      slug: 'yoshi',
      name: 'Yoshi',
      color: '#83cd65',
      tier: 'S',
    },
    {
      slug: 'mewtwo',
      name: 'Mewtwo',
      color: '#7859bd',
      tier: 'S',
    },
    {
      slug: 'roy',
      name: 'Roy',
      color: '#83b366',
      tier: 'A',
    },
    {
      slug: 'link',
      name: 'Link',
      color: '#4393be',
      tier: 'A',
    },
    {
      slug: 'young-link',
      name: 'Young Link',
      color: '#afce6f',
      tier: 'A',
    },
    {
      slug: 'richter',
      name: 'Richter',
      color: '#396dab',
      tier: 'A',
    },
    {
      slug: 'simon',
      name: 'Simon',
      color: '#6d1e15',
      tier: 'A',
    },
    {
      slug: 'shulk',
      name: 'Shulk',
      color: '#c76b7b',
      tier: 'A',
    },
    {
      slug: 'ike',
      name: 'Ike',
      color: '#b74f3e',
      tier: 'A',
    },
    {
      slug: 'cloud',
      name: 'Cloud',
      color: '#409384',
      tier: 'A',
    },
    {
      slug: 'megaman',
      name: 'Megaman',
      color: '#85c1e0',
      tier: 'A',
    },
    {
      slug: 'toon-link',
      name: 'Toon Link',
      color: '#a1e293',
      tier: 'A',
    },
    {
      slug: 'palutena',
      name: 'Palutena',
      color: '#a4e2c3',
      tier: 'A',
    },
    {
      slug: 'pit',
      name: 'Pit',
      color: '#7db3d4',
      tier: 'A',
    },
    {
      slug: 'dark-pit',
      name: 'Dark Pit',
      color: '#8061b8',
      tier: 'A',
    },
    {
      slug: 'fox',
      name: 'Fox',
      color: '#407dd8',
      tier: 'A',
    },
    {
      slug: 'pokemon-trainer',
      name: 'Pokémon Trainer',
      color: '#81a4cc',
      tier: 'A',
    },
    {
      slug: 'sonic',
      name: 'Sonic',
      color: '#649dec',
      tier: 'A',
    },
    {
      slug: 'donkey-kong',
      name: 'Donkey Kong',
      color: '#fada4a',
      tier: 'A',
    },
    {
      slug: 'snake',
      name: 'Snake',
      color: '#6a8196',
      tier: 'A',
    },
    {
      slug: 'lucas',
      name: 'Lucas',
      color: '#e06833',
      tier: 'A',
    },
    {
      slug: 'ness',
      name: 'Ness',
      color: '#de423d',
      tier: 'A',
    },
    {
      slug: 'samus',
      name: 'Samus',
      color: '#353f56',
      tier: 'A',
    },
    {
      slug: 'dark-samus',
      name: 'Dark Samus',
      color: '#3c3a5c',
      tier: 'A',
    },
    {
      slug: 'bowser',
      name: 'Bowser',
      color: '#44745e',
      tier: 'A',
    },
    {
      slug: 'ryu',
      name: 'Ryu',
      color: '#d0504d',
      tier: 'A',
    },
    {
      slug: 'ken',
      name: 'Ken',
      color: '#82a7b7',
      tier: 'A',
    },
    {
      slug: 'bayonetta',
      name: 'Bayonetta',
      color: '#a5a1e0',
      tier: 'A',
    },
    {
      slug: 'rob',
      name: 'R.O.B.',
      color: '#b3b9be',
      tier: 'A',
    },
    {
      slug: 'isabelle',
      name: 'Isabelle',
      color: '#9bb37e',
      tier: 'A',
    },
    {
      slug: 'villager',
      name: 'Villager',
      color: '#5da972',
      tier: 'A',
    },
    {
      slug: 'mii-swordfighter',
      name: 'Mii Swordfighter',
      color: '#5f6bb1',
      tier: 'A',
    },
    {
      slug: 'zero-suit-samus',
      name: 'Zero Suit Samus',
      color: '#1e5ba4',
      tier: 'A',
    },
    {
      slug: 'meta-knight',
      name: 'Meta Knight',
      color: '#2e3e76',
      tier: 'A',
    },
    {
      slug: 'diddy-kong',
      name: 'Diddy Kong',
      color: '#e15951',
      tier: 'A',
    },
    {
      slug: 'pichu',
      name: 'Pichu',
      color: '#d4c083',
      tier: 'A',
    },
    {
      slug: 'wario',
      name: 'Wario',
      color: '#f7cc64',
      tier: 'A',
    },
    {
      slug: 'king-k-rool',
      name: 'King K. Rool',
      color: '#6d8545',
      tier: 'A',
    },
    {
      slug: 'luigi',
      name: 'Luigi',
      color: '#5ea444',
      tier: 'B',
    },
    {
      slug: 'dr-mario',
      name: 'Dr. Mario',
      color: '#e86c6d',
      tier: 'B',
    },
    {
      slug: 'mario',
      name: 'Mario',
      color: '#d04c4a',
      tier: 'B',
    },
    {
      slug: 'wolf',
      name: 'Wolf',
      color: '#868686',
      tier: 'B',
    },
    {
      slug: 'incineroar',
      name: 'Incineroar',
      color: '#fad94a',
      tier: 'B',
    },
    {
      slug: 'ganondorf',
      name: 'Ganondorf',
      color: '#7d7a97',
      tier: 'B',
    },
    {
      slug: 'falco',
      name: 'Falco',
      color: '#69b1df',
      tier: 'B',
    },
    {
      slug: 'mii-gunner',
      name: 'Mii Gunner',
      color: '#e2b975',
      tier: 'B',
    },
    {
      slug: 'pac-man',
      name: 'Pac Man',
      color: '#f3b758',
      tier: 'B',
    },
    {
      slug: 'wii-fit-trainer',
      name: 'Wii Fit Trainer',
      color: '#a6d18a',
      tier: 'B',
    },
    {
      slug: 'captain-falcon',
      name: 'Captain Falcon',
      color: '#8c8cd6',
      tier: 'B',
    },
    {
      slug: 'corrin',
      name: 'Corrin',
      color: '#72a6bd',
      tier: 'B',
    },
    {
      slug: 'zelda',
      name: 'Zelda',
      color: '#fbeaac',
      tier: 'B',
    },
    {
      slug: 'robin',
      name: 'Robin',
      color: '#ba8bd4',
      tier: 'B',
    },
    {
      slug: 'rosalina',
      name: 'Rosalina',
      color: '#9cded5',
      tier: 'B',
    },
    {
      slug: 'greninja',
      name: 'Greninja',
      color: '#5673a5',
      tier: 'B',
    },
    {
      slug: 'ice-climbers',
      name: 'Ice Climbers',
      color: '#a7caf9',
      tier: 'B',
    },
    {
      slug: 'sheik',
      name: 'Sheik',
      color: '#746fd0',
      tier: 'B',
    },
    {
      slug: 'jigglypuff',
      name: 'Jigglypuff',
      color: '#e18ae5',
      tier: 'B',
    },
    {
      slug: 'ridley',
      name: 'Ridley',
      color: '#6b486d',
      tier: 'B',
    },
    {
      slug: 'mii-brawler',
      name: 'Mii Brawler',
      color: '#8e3838',
      tier: 'B',
    },
    {
      slug: 'mr-game-watch',
      name: 'Mr. Game & Watch',
      color: '#a6a392',
      tier: 'B',
    },
    {
      slug: 'king-dedede',
      name: 'King Dedede',
      color: '#fde87b',
      tier: 'B',
    },
    {
      slug: 'bowser-jr',
      name: 'Bowser Jr.',
      color: '#74bb4e',
      tier: 'B',
    },
    {
      slug: 'duck-hunt',
      name: 'Duck Hunt',
      color: '#865f40',
      tier: 'B',
    },
    {
      slug: 'kirby',
      name: 'Kirby',
      color: '#f2c1c4',
      tier: 'C',
    },
    {
      slug: 'little-mac',
      name: 'Little Mac',
      color: '#688d74',
      tier: 'C',
    },
  ],
};
